### PR TITLE
Fix error and add cards / series

### PR DESCRIPTION
**Pull request by isaaclepes**
cards.yml
Correct duplicate model id Squid (3200076) also listed for Wither Skeleton should be (3200082). Add cards for parity with resource pack 3.0.0 (ID's 88-100). Includes Halloween, winter, and valentines series cards. Also includes dark brown, creamy, gray, white horses.

series.yml
Add series for winter, valentines (all in disabled state).

### CODE REVIEW

**Comment by isaaclepes** [comment]
Version 3.0.0 of resource pack:
https://github.com/isaaclepes/TradingCardsResource/releases/tag/v3

**Comment by isaaclepes** [comment]
Latest commits added entries for other vanilla mobs, including:

Salmon, Cod, Tropical Fish, Vindicator, Pillager, Illusioner, Evoker, Warm Frog, Cold Frog, Temperate Frog, Normal Panda, Weak Panda, Aggressive Panda, Playful Panda, Brown Panda, Goat, Hoglin, Allay, Warden, Red Parrot, Blue Parrot, Green Parrot, Cyan Parrot, and Gray Parrot.

And series (also default disabled) for Spring and Summer with a selection of the new cards assigned for both.

**Comment by sarhatabaot** [comment]
lgtm, I'll test it out after I finish working on #61

**Review by sarhatabaot — APPROVED** [review]
lgtm

**Pull request merged**
